dtinfo other files

diff --git a/cde/admin/IntegTools/dbTools/mkProd b/cde/admin/IntegTools/dbTools/mkProd
--- a/cde/admin/IntegTools/dbTools/mkProd
+++ b/cde/admin/IntegTools/dbTools/mkProd
@@ -517,12 +517,12 @@ doit()
 		# set permissions for non-links
 		if [ "${TYPE%link}" = "$TYPE" ]; then
 			if [ "$USER" = "root" ]; then
-				chmod $MODE $DEST || 
-					echo "ERROR: \"chmod $MODE $DEST\" failed" >&2
 				chgrp $GROUP $DEST || 
 					echo "ERROR: \"chgrp $GROUP $DEST\" failed" >&2
 				chown $OWNER $DEST || 
 					echo "ERROR: \"chown $OWNER $DEST\" failed" >&2
+				chmod $MODE $DEST ||
+					echo "ERROR: \"chmod $MODE $DEST\" failed" >&2
 			fi
 		fi
 
